nuxt-modules/og-image

- src/runtime/nitro/renderers/browser.ts
Currently, after making a screenshot, the browser does not close, which generates a lot of processes and leads to memory leaks. This pull-request adds closing the browser after taking a screenshot
> fix: Close browser after use

- .playground/components/islands/CustomFontTemplate.vue
- .playground/nuxt.config.ts
- .playground/pages/index.vue
- .playground/pages/satori/custom-font.vue
- README.md
- src/module.ts
- src/runtime/nitro/renderers/satori/index.ts
- src/runtime/nitro/renderers/satori/utils.ts
- src/runtime/nitro/routes/html.ts
- src/types.ts
Allows custom local fonts to be loaded easily through the config.
```ts
ogImage: {
fonts: [
{
name: 'optieinstein',
weight: 800,
path: '/OPTIEinstein-Black.otf',
}
]
}
```
https://github.com/harlan-zw/nuxt-og-image/issues/42
> feat: support locally loaded custom fonts

- src/runtime/nitro/utils-pure.ts
There might be a `nonce` attribute added to script tags, e.g. by `nuxt-security`, which makes the regex not match the script tag anymore. This change loosens the regex a bit so that it only checks for the script's `id`, which should be unique.
n/a
n/a
> fix(utils-pure): generalize script matcher

- src/runtime/nitro/middleware/og.png.ts
Currently, the cache is forced to 365 days; I have adjusted it with the custom-defined value.
> fix: sync Cache-Control header time with options

- src/module.ts
Actually, it's not possible to use `Roboto:400,700`. We have to define it in multiple lines.
> doc: update fonts example in types

- src/build/build.ts
- src/compatibility.ts
- src/module.ts
Resolves #143 
This PR adds support for the `cloudflare_module` preset of Nitro.
- For runtime compatibility, it is the same as `cloudflare` and `cloudflare-pages`.
- The font asset behavior is similar to `cloudflare`, so I include it with the conditional on `module.ts`.
- The behavior of compiled wasm is similar to `cloudflare-pages`, so I added `isCloudflarePagesOrModule` on nitro `compiled` hook.
> feat: `cloudflare_module` support

- src/runtime/nuxt/components/Templates/Community/Frame.vue
this PR adds a new template for ogImage.
the default look will be like:
and in a project:
> feat: `Frame` community template

- src/build/devtools.ts
We are planning to move to [emitting absolute paths in `builder:watch` in Nuxt v4](https://github.com/nuxt/nuxt/issues/25339). You can see a little more about the history in the PR linked in that issue.
This PR is an attempt to use a forward/backward compatible approach, namely resolving the path to ensure it's absolute, then making it relative so your existing code will continue to work.
This should be safe to merge as is, but do let me know if you have any concerns about this approach.
> fix: adopt forward-compatible approach to `builder:watch`

- package.json
- pnpm-lock.yaml
- src/runtime/nitro/og-image/bindings/chromium/on-demand.ts
Fixes #212
1. The licensing issues
The 'terminate' package is licensed under GPL-2.0: https://github.com/dwyl/terminate/blob/main/LICENSE
However, this og-image package is licensed under MIT.
Because 'terminate' was being used in the og-image *runtime* rather than as a dev tool as the author of 'terminate' intended...:
https://github.com/dwyl/terminate/issues/35#issuecomment-441572754
... this caused og-image to be a work derived from GPL-licensed code.
As per GPL-2.0 section 2 point B:
> https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html#section2
> You must cause any work that you distribute or publish, that in
whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License. …
> fix: stop using 'terminate' package to avoid GPL

- .github/workflows/release.yml
- .github/workflows/test.yml
- package.json
setup-node can reference the engine options in package.json as the node version.
- https://github.com/actions/setup-node?tab=readme-ov-file#usage
Using the `engine` makes it easier to manage workflow versions.
> chore(ci): use `node-version-file` option

- src/runtime/nuxt/components/Templates/Community/Nuxt.vue
- src/runtime/nuxt/components/Templates/Community/Pergel.vue
Resolves #226 
Fixes the pergel example : setting a headline doesn't work.
Also fixed the `@see` comment for Pergel and Nuxt examples.
> fix: nuxt and pergel community template issues

- src/module.ts
In the latest version of Nuxt, ``nuxt.options.dir.public`` may be an absolute path.
> fix: resolve ``publicDirAbs`` correctly

- .github/renovate.json5
- renovate.json
related nuxt-modules/sitemap#292
As with Nuxt Sitemap, I moved the Renovate config to `.github/`.
Also, I rename from `renovate.json` to `renovate.json5`. `renovate.json5` is able to add comment.
- ref: https://docs.renovatebot.com/configuration-options/
> chore(ci): move renovate config

- docs/content/3.guides/3.cache.md
The `cacheMaxAgeSeconds` is defined as seconds and not as `milliseconds`. Just use the value of 7 days instead of 7.000 days.
> docs: align `cacheMaxAgeSeconds` value with comment

- src/logger.ts
- src/module.ts
- src/runtime/app/composables/defineOgImage.ts
- src/runtime/logger.ts
#286
For users who don't quite understand the magic of Nuxt SSR or how OG Image tags need to work, it's quite easy to use the `defineOgImage*` composables in a way where no image is generated.
This appears when users try to call these functions client-side only, as either we'll be inserting the `og:image` payload too late for Nuxt OG Image to generate the image or inserting the tags too late for any bots to pick them up.
Previously no warning was shown and it would silently fail in these instances, this was because we were tree-shaking these composables out client-side.
This PR changes it so we avoid tree-shaking them in development, allowing us to show an error message that can be debugged.
```vue
<script lang="ts" setup>
defineOgImageComponent('MyComponent', {
foo: 'bar',
})
</script> …
```
> fix: throw error when using `defineOgImage*` fns client-side

- src/runtime/server/og-image/satori/plugins/imageSrc.ts
Resolves #312
Properly decodes html image sources with query parameters and other encoded string values due to fetchIsland changing url format.
> fix: decode image src with html string

- client/app.vue
- client/components/OCodeBlock.vue
- client/composables/shiki.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
|           |  gziped (`- 1.5 MB`)  | unpacked |
| :-------: | :------: | :------: |
| `v4.1.3`  |  2.1 MB  | 10.7 MB  |
| optimized | 518.6 kB |  1.7 MB  |
- Use [fine grained bundle](https://shiki.style/guide/bundles#fine-grained-bundle) to only bundle needed languages and themes.
- Use [Javascript RegExp Engine](https://shiki.style/guide/regex-engines#javascript-regexp-engine).
- Use `xml` for svg highlighting (removes dependency on lang/javascript ~30kb gziped).
I will create PRs for other similar repos like `nuxt/scripts` & the seo suite once this PR is reviewed 🚀
> perf(devtools): optimize shiki bundle size

- src/runtime/server/og-image/context.ts
Disabling the cache by setting `cacheMaxAgeSecond` to 0 in `defineOgImageComponent` (as per the documentation, https://nuxtseo.com/docs/og-image/guides/cache#bypassing-the-cache), for example
```typescript
defineOgImageComponent('NuxtSeo', {
title: 'Test'
}, {
cacheMaxAgeSeconds: 0
})
```
does not work and returns the default value (259200 seconds).
This is because when the og image options are extracted to generate the h3 context any falsy value is deleted from the payload: https://github.com/nuxt-modules/og-image/blob/0a698094e17663fcd5bfa805b91a4041ac06c0b4/src/runtime/server/og-image/context.ts#L158-L162
This seems to be intentional as the comment states, so I only added an extra check to avoid deleting options that have the value `0`.
With this change setting `cacheMaxAgeSeconds` to …
> fix: disabling cache by template not working

- src/runtime/server/og-image/context.ts
- test/fixtures/i18n/app.vue
- test/fixtures/i18n/i18n/locales/en.ts
- test/fixtures/i18n/i18n/locales/es.ts
- test/fixtures/i18n/i18n/locales/fr.ts
- test/fixtures/i18n/nuxt.config.ts
- test/fixtures/i18n/pages/index.vue
https://github.com/nuxt-modules/og-image/issues/326
The cache key is changing as the site config URL changes at different stages based on the Nuxt I18n `baseUrl`.
To fix this we omit the site URL segment in the cache generation when prerendering as there can only be a single host
> fix(prerender,i18n): broken cache key

- pnpm-lock.yaml
- src/build/build.ts
- src/compatibility.ts
resolves https://github.com/nuxt-modules/og-image/issues/332
unenv v2 has some breaking changes in paths. alternatively we could add as a dependency and resolve the path fully, but as v5 already requires nuxt v3.16, this is probably safe.
> fix: unenv paths

- client/components/TemplateComponentPreview.vue
Potential fix for [https://github.com/nuxt-modules/og-image/security/code-scanning/4](https://github.com/nuxt-modules/og-image/security/code-scanning/4)
To fix the problem, we need to ensure that all occurrences of the '>' character are replaced, not just the first one. This can be achieved by using a regular expression with the global flag (`g`). Specifically, we will replace the line that uses `replace('>', '')` with `replace(/>/g, '')`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: safer string escape

- src/runtime/server/util/encoding.ts
Potential fix for [https://github.com/nuxt-modules/og-image/security/code-scanning/5](https://github.com/nuxt-modules/og-image/security/code-scanning/5)
To fix the problem, we need to ensure that the `&amp;` entity is decoded last in the `decodeHtml` function. This will prevent any double unescaping issues by ensuring that `&amp;` is not prematurely converted to `&` before other entities are fully decoded.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: re-order escaping

- client/app.vue
- client/components/CreateOgImageDialog.vue
- client/components/TemplateComponentPreview.vue
- client/composables/fetch.ts
- client/composables/rpc.ts
- client/composables/templates.ts
- src/build/devtools.ts
- src/module.ts
- src/rpc-types.ts
https://github.com/nuxt-modules/og-image/issues/343
Allows you click the "Eject" button in the devtools to create the current component in your own directory. This is useful as you don't need to remember what the og image component dirs are and you don't need to manually copy+paste the file over.
> feat(devtools): eject templates

- playground/pages/prebuilt-reactive.vue
- playground/pages/satori/reactive-props.vue
- src/runtime/app/composables/defineOgImage.ts
- src/runtime/app/utils.ts
- src/runtime/app/utils/plugins.ts
- src/runtime/pure.ts
- src/runtime/shared.ts
- src/runtime/types.ts
#360
Reactive props should just work.
```ts
const name = ref('foo')
defineOgImage({
url: () => `https://nitro.build/_og/guide/tasks.png?name=${name.value}&title=Tasks&description=Nitro+tasks+allow+on-off+operations+in+runtime.`,
width: 1200,
height: 630,
alt: 'Nitro UI',
})
name.value = 'bar'
```
:warning: This change is a bit risky as we're reworking how we resolve props
> fix: support reactive og image options & props

- src/runtime/server/og-image/satori/transforms/inlineCss.ts
this is a change in nuxt v4 - these arrays are now optional
(opened https://github.com/nuxt-modules/og-image/pull/369 to address the snapshot failure, which also occurs on ecosystem-ci)
> fix: handle undefined `link`/`style` in server component response

- client/app.vue
- playground/components/OgImage/WithImage.vue
- playground/nuxt.config.ts
- playground/pages/satori/jpeg.vue
- src/module.ts
- src/runtime/server/og-image/satori/renderer.ts
- src/runtime/types.ts
- test/integration/dev-debugging.test.ts
https://github.com/nuxt-modules/og-image/issues/367
JPEG support via `sharp` is still quite unstable, this PR aims to get it slightly more stable by adding several checks when we try and render at runtime.
We also loosen up the compatibility checks. If `sharp` is installed and the target supports it, then we try and see if it can be imported, if so, then we switch to it.
There's cases where `sharp` may be installed and supported but can't be imported, this is quite common for CI environments where it can't install the correct binary needed.
This _might_ introduce some regressions related to these resolutions but hoppefully the get caught with the `catch(() => {})`, it's difficult to test it.
> fix: reworked `sharp` compatibility checks for JPEG rendering
