nuxt-modules/og-image

README.md

doc: polish

---

.playground/nuxt.config.ts
.playground/package.json
client/app.vue
client/components/IFrameLoader.vue
client/components/ImageLoader.vue
client/composables/devtools-client.ts
client/package.json
client/pages/options.vue
client/pages/png.vue
client/pages/svg.vue
client/pages/vnodes.vue
client/util/logic.ts
package.json
pnpm-lock.yaml
src/module.ts
src/runtime/nitro/routes/__og_image__/html.ts

feat: nuxt devtools integration

---

README.md

doc: mask -> selector: typo

---

.playground/nuxt.config.ts
.playground/pages/index.vue
.playground/pages/satori/with-options.vue
README.md
src/runtime/components/OgImageBasic.island.vue

Adding some options to the default template:
- `background`
- `padding`
- `titleFontSize`
- `descriptionFontSize`

feat: add options to the default template

---

package.json
pnpm-lock.yaml
src/runtime/nitro/renderers/satori/index.ts

Updates all dependencies for v1, primarily to make use of the most recent version of @nuxt/kit for compatibility with Node 19 and 20.
https://github.com/harlan-zw/nuxt-seo-kit/issues/47
https://github.com/harlan-zw/nuxt-seo-kit/issues/52 mentions a similar goal.

chore(deps): update

---

package.json
pnpm-lock.yaml

Fixing the nuxt/kit version sometimes leads to typescript errors due to a difference in the types in two versions of nuxt/kit.

 chore: loosen nuxt kit version

---

src/module.ts

See https://github.com/unjs/nitro/pull/1274
Hacky solution until the above is patched.
https://github.com/harlan-zw/nuxt-og-image/issues/52

fix: netlify images not working

---

src/module.ts

I think it makes sense even with having less :wink: 
n/a
n/a

fix: broken dynamic types output

---

.nuxtrc
src/module.ts

follow up to https://github.com/harlan-zw/nuxt-og-image/pull/126, this adds types for unocss/tailwindcss so we can build the module again - sorry!

chore: add module types to build environment

---

src/runtime/nitro/og-image/satori/plugins/imageSrc.ts
src/runtime/pure.ts

https://github.com/nuxt-modules/og-image/pull/201

fix: images broken for non-jpeg, extension-less paths

---

package.json
pnpm-lock.yaml
src/compatibility.ts
src/runtime/nitro/og-image/bindings/css-inline/node.ts
src/runtime/nitro/og-image/satori/instances.ts
src/runtime/nitro/og-image/satori/transforms/inlineCss.ts
test/integration/endpoints/debug.test.ts

https://github.com/nuxt-modules/og-image/issues/170, https://github.com/harlan-zw/nuxt-seo/issues/266
The trade-off on performance and more stable installs for Mac users.

fix: prefer wasm `@css-inline/css-inline` dep

---

client/app.vue
client/components/TwitterCardRenderer.vue

fix(devtools): better UI for twitter title

---

src/runtime/nitro/og-image/satori/transforms/inlineCss.ts
src/runtime/nitro/og-image/satori/vnodes.ts

fix: stricter opt-in for inline styling

---

.github/ISSUE_TEMPLATE/01-feature-suggestion.yml
.github/ISSUE_TEMPLATE/02-bug-report.yml
.github/ISSUE_TEMPLATE/03-documentation.yml
.github/ISSUE_TEMPLATE/04-help-wanted.yml
.github/ISSUE_TEMPLATE/config.yml

related nuxt-modules/sitemap#323
I added the same issue templates as I added in Nuxt Scripts.

chore(ci): add GitHub Issue templates

---

test/integration/endpoints/fonts.test.ts

Currently test suites are failing because of a new version of the Inter font - this should hopefully unbreak CI for both this module + also https://github.com/nuxt/ecosystem-ci.

test: update snapshot

---

src/module.ts

fix: respect configured `componentIslands` value

---

src/runtime/app/utils.ts
src/runtime/server/og-image/context.ts

fix: improve prerendering error debugging

---

docs/content/0.getting-started/5.getting-familar-with-nuxt-og-image.md

docs: fix broken link

---

docs/content/0.getting-started/5.getting-familar-with-nuxt-og-image.md

Fixed a typo in the documentation, probably coming from two versions of the text being merged.
Also, the example images in the doc ([like here](https://nuxtseo.com/docs/og-image/getting-started/getting-familar-with-nuxt-og-image#part-2-customising-nuxtseo-template)) are not properly displayed (on my side), should I open an issue for that?

Fix typo in doc

---

package.json
pnpm-lock.yaml
src/runtime/mock/empty.ts
src/runtime/mock/proxy-cjs.ts

this entirely drops `unenv` dep in favour of inlined empty object

perf: inline mock empty

---

docs/content/3.guides/6.icons-and-images.md

fix: Fixed typo in title
